language: node_js
node_js:
    - "0.10"

services:
    - mongodb

script:
    - npm test
    - ./node_modules/.bin/lsc parser/law_parser.ls
    - ./node_modules/.bin/lsc parser/pcode_parser.ls
    - ./node_modules/.bin/lsc import.ls

notifications:
    irc: "chat.freenode.net#laweasyread"
